# ----------------------------------------------------------------------
# This file was generated by C:\Users\L\Miniconda3\Scripts\img2py
#
from wx.lib.embeddedimage import PyEmbeddedImage

ei = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAACQUlEQVRYR+2VzWsTQRjGn9mP'
    b'bLYb0l0QrASxFw+KkBUvPdX02CxCqBdvelFQEJs/oLQi3nso1IsQ/4IiutFb680evWgufl3E'
    b'mz3pNtmdkZl0w8aEnW0XGpAMhJ3dfed5f/PMu28IJjzIhPNjCvB/OPCgXncp8AiEzKfWFGMv'
    b'nrXbrWRMbgd4ckbILgA7Q0EfbPu+kwpwp1azTdOsZhDrhxCyCULccfERpWCUileKqkIhBNu+'
    b'P7TpEQfu1+vfQMiFcYKUMdAoEq/4nCeI5/xezHnSo3lSwzQMGLouB7i3vMy6vR7CI3EuFieN'
    b'BfupgMuuizNzcyg7Di5VqygYBmYdB0XTFD/dKEBVNXzY38fm2hrKliUHeLiywq4uLsJdWMC5'
    b'SkUkKhSLsEpW30ZFFc9UtX+VjW73EJ8/fsLTZlMC8IbNg0a8mNIrGYBbBtYvKmiclddwEAT4'
    b'2ulkAHjVq0ER1Zx57FyTQ8QAT1ZXYZdKKUdwAgBb426ku8Br6DAI8KXTgaZp+FG50sKM2sQS'
    b'ORAf0WC7u8zG7+hX5u3nCaRsCTf0vWEAfueHcYHnkZevTQHgtszKFXJGzKjO6BEIB3p7ALme'
    b'U16+3NMGRz9cQacD8B2eNvjUhwFehy0Q3JZvIU8EewdPr8UK/zqwAZD1PPIZ1r6EpzUmCMAe'
    b'w9M3xgO0wwYYdjLsIkdIGsAJuuGxSRI9YLQRTRzgNLphogmNOgDg/Nb7538s++axrc2wQAuD'
    b'tz/vureSofI/9AzCeUKmAFMH/gKp9sghCZcLcQAAAABJRU5ErkJggg==')

